"Resource/UI/HudPlayerHealth.res"
{
	"HudPlayerHealth"
	{
		"ControlName"           					"EditablePanel"
		"fieldName"	            					"HudPlayerHealth"
		"xpos"		               					"0"
		"ypos"		               					"0"
		"zpos"		               					"2"
		"wide"		              					"f0"
		"tall"			           				 	"480"
		"visible"	              					"1"
		"enabled"		           					"1"
		"HealthBonusPosAdj"     					"35"
		"HealthDeathWarning"    					"0.49"
		"HealthDeathWarningColor"					"HUDDeathWarning"
	}

	//==================================================================================================================================================
	// HEALTH ANCHOR
	// This element can be used to move all the health elements at the same time
	//==================================================================================================================================================

	"HealthAnchor"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"HealthAnchor"
		"xpos"										"c-180"
		"ypos"										"c70"
		"zpos"										"0"
		"wide"										"2"
		"tall"										"80"
		"visible"									"0"
		"enabled"									"1"
		"alpha"										"0"
	}
	
	//==================================================================================================================================================
	// BUNNY
	//==================================================================================================================================================
	
	"Bunny"
	{
		"controlName"	"ImagePanel"	"fieldName"	"Bunny"
		"xpos"	"-30"	"ypos"	"-55"	"zpos"	"-100"	"wide"	"40"	"tall"	"40"
		"visible"	"0"	"enabled"	"1"	"image"	"replay/thumbnails/bunny"	"scaleImage"	"1"
		"pin_to_sibling"	"HealthAnchor"	"pin_corner_to_sibling"	"PIN_CENTER_TOP"	"pin_to_sibling_corner"	"PIN_CENTER_TOP"
	}

	//==================================================================================================================================================
	// BUFF - HURT CROSS
	//==================================================================================================================================================

	"PlayerStatusHealthBonusImage"
	{
		"ControlName"	         				 	"ImagePanel"
		"fieldName"		         				 	"PlayerStatusHealthBonusImage"
		"xpos"			         				 	"c-193+999"
		"ypos"			         				 	"c96+1"
		"zpos"			         				 	"-4"
		"wide"			         				 	"28"
		"tall"			         				 	"28"
		"visible"		         				 	"0"
		"enabled"		         				 	"1"
		"image"			         				 	"../hud/health_over_bg"
		"scaleImage"	         				 	"1"
	}

	//==================================================================================================================================================
	// PLAYER HEALTH
	//==================================================================================================================================================
	"cross"
	{
		"ControlName" "ImagePanel" "fieldName" "cross"
		"xpos" "cs-0.5" "ypos" "cs-0.5" "zpos" "100"	"wide" "180" "tall" "180" "drawcolor" "255 255 255 255"
		"visible" "0" "enabled" "1" "scaleImage" "1"	"image" "replay/thumbnails/crosshairs/outsidew"
	}
	"cross1"
	{
		"ControlName" "ImagePanel" "fieldName" "cross1"
		"xpos" "cs-0.5" "ypos" "cs-0.5" "zpos" "100"	"wide" "180" "tall" "180"
		"visible" "0" "enabled" "1" "scaleImage" "1"	"image" "replay/thumbnails/crosshairs/outsideg"
	}
		"cross2"
	{
		"ControlName" "ImagePanel" "fieldName" "cross2"
		"xpos" "cs-0.5" "ypos" "cs-0.5" "zpos" "100"	"wide" "140" "tall" "140"
		"visible" "0" "enabled" "1" "scaleImage" "1"	"image" "replay/thumbnails/crosshairs/dot" "drawcolor" "0 0 0 255"
	}

	"a"
	{
		"ControlName"	         				 	"ImagePanel"
		"fieldName"		         				 	"a"
		"xpos"			         				 	"cs-0.5"
		"ypos"			         				 "cs-0.5"
		"zpos"			         				 	"-99"
		"wide"			         				 	"1"
		"tall"			         				 	"1"
		"visible"		         				 	"0"
		"enabled"		         				 	"1"
		"scaleImage"	         				 	"1"
		"fillcolor" "255 255 255 255"
	}
		"a2"
	{
		"ControlName"	         				 	"ImagePanel"
		"fieldName"		         				 	"a2"
		"xpos"			         				 	"cs-0.5"
		"ypos"			         				 "cs-0.5"
		"zpos"			         				 	"-99"
		"wide"			         				 	"14"
		"tall"			         				 	"1"
		"visible"		         				 	"0"
		"enabled"		         				 	"1"
		"scaleImage"	         				 	"1"
		"fillcolor" "255 255 255 255"
	}
	"b"
	{
		"ControlName"	         				 	"ImagePanel"
		"fieldName"		         				 	"b"
		"xpos"			         				 	"cs-0.5"
		"ypos"			         				 "cs-0.5"
		"zpos"			         				 	"-100"
		"wide"			         				 	"2"
		"tall"			         				 	"2"
		"visible"		         				 	"0"
		"enabled"		         				 	"1"
		"scaleImage"	         				 	"1"
		"fillcolor" "0 0 0 205"
	}
		"b2"
	{
		"ControlName"	         				 	"ImagePanel"
		"fieldName"		         				 	"b2"
		"xpos"			         				 	"cs-0.5"
		"ypos"			         				 "cs-0.5"
		"zpos"			         				 	"-100"
		"wide"			         				 	"15"
		"tall"			         				 	"2"
		"visible"		         				 	"0"
		"enabled"		         				 	"1"
		"scaleImage"	         				 	"1"
		"fillcolor" "0 0 0 255"
	}
	"statusicon"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"statusicon"
		"xpos"		    	         				"9"
		"ypos"		    	         				"r55"
		"zpos"		    	         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"		  	         				"1"
		"enabled"	  		         				"1"
		"labelText" 		         				"¦"
		"textAlignment"         				 	"west"
		"font"                   				 	"m0refont16typoster"
		"fgcolor"	    	         				"Health Numbers"
	}
		"statusiconShadow"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"statusiconShadow"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"		  	         				"1"
		"enabled"	  		         				"1"
		"labelText" 		         				"¦"
		"textAlignment"         				 	"west"
		"font"                   				 	"m0refont16typosterblur"
		"fgcolor"	    	         				"black"

		"pin_to_sibling"							"statusicon"
	}
			"statusiconShadow2"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"statusiconShadow2"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"		  	         				"1"
		"enabled"	  		         				"1"
		"labelText" 		         				"¦"
		"textAlignment"         				 	"west"
		"font"                   				 	"m0refont16typosterblur"
		"fgcolor"	    	         				"black"

		"pin_to_sibling"							"statusicon"
	}
				"statusiconShadow3"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"statusiconShadow3"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"		  	         				"1"
		"enabled"	  		         				"1"
		"labelText" 		         				"¦"
		"textAlignment"         				 	"west"
		"font"                   				 	"m0refont16typosterblur"
		"fgcolor"	    	         				"black"

		"pin_to_sibling"							"statusicon"
	}
				"statusiconShadow4"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"statusiconShadow4"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"		  	         				"1"
		"enabled"	  		         				"1"
		"labelText" 		         				"¦"
		"textAlignment"         				 	"west"
		"font"                   				 	"m0refont16typosterblur"
		"fgcolor"	    	         				"black"

		"pin_to_sibling"							"statusicon"
	}
				"statusiconShadow5"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"statusiconShadow5"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"		  	         				"1"
		"enabled"	  		         				"1"
		"labelText" 		         				"¦"
		"textAlignment"         				 	"west"
		"font"                   				 	"m0refont16typosterblur"
		"fgcolor"	    	         				"black"

		"pin_to_sibling"							"statusicon"
	}
				"statusiconShadow6"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"statusiconShadow6"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"		  	         				"1"
		"enabled"	  		         				"1"
		"labelText" 		         				"¦"
		"textAlignment"         				 	"west"
		"font"                   				 	"m0refont16typosterblur"
		"fgcolor"	    	         				"black"

		"pin_to_sibling"							"statusicon"
	}
				"statusiconShadow7"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"statusiconShadow7"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"		  	         				"1"
		"enabled"	  		         				"1"
		"labelText" 		         				"¦"
		"textAlignment"         				 	"west"
		"font"                   				 	"m0refont16typosterblur"
		"fgcolor"	    	         				"black"

		"pin_to_sibling"							"statusicon"
	}
	
	"PlayerStatusHealthValue"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusHealthValue"
		"xpos"		    	         				"26+5"
		"ypos"		    	         				"r60"
		"zpos"		    	         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"		  	         				"1"
		"enabled"	  		         				"1"
		"labelText" 		         				"%Health%"
		"textAlignment"         				 	"west"
		"font"                   				 	"m0refont32"
		"fgcolor"	    	         				"Health Numbers"

	}

			"healthbar"
	{	
		"ControlName"	"CBuildingHealthBar"	"fieldName"	"healthbar"
		"xpos"	"-102+2"	"ypos"	"-42"	"zpos"	"10"	"wide"	"66"	"tall"	"10"	"textAlignment"	"Left"
		"visible"	"1"	"enabled"	"1"
		"variable"	"Health"
		"FGcolor_override"		"255 255 255 255" "BGcolor_override"		"75 75 75 128"	"alpha"	"225"
		"pin_to_sibling"	"PlayerStatusHealthValue"	"pin_corner_to_sibling"	"PIN_TOPLEFT"	"pin_to_sibling_corner"	"PIN_TOPRIGHT"
	}
		"healthbarblur"
	{
		"controlName"	"ImagePanel"	"fieldName"	"healthbarblur"
		"xpos"	"-100-12+2"	"ypos"	"-41""zpos"	"-100"	"wide"	"87"	"tall"	"13"
		"visible"	"1"	"enabled"	"1"	"image"	"replay/thumbnails/health"	"scaleImage"	"1" "drawcolor" "black" "alpha" "225"
		"pin_to_sibling"	"PlayerStatusHealthValue"	"pin_corner_to_sibling"	"PIN_TOPLEFT"	"pin_to_sibling_corner"	"PIN_TOPRIGHT"
	}
	"PlayerStatusHealthValueShadow"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusHealthValueShadow"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%Health%"
		"textAlignment"	         				 	"west"
		"font"                   				 	"m0refont32blur"
		"fgcolor"	     	         				"Black"

		"pin_to_sibling"							"PlayerStatusHealthValue"
	}
		"PlayerStatusHealthValueShadow2"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusHealthValueShadow2"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%Health%"
		"textAlignment"	         				 	"west"
		"font"                   				 	"m0refont32blur"
		"fgcolor"	     	         				"Black"

		"pin_to_sibling"							"PlayerStatusHealthValue"
	}
			"PlayerStatusHealthValueShadow3"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusHealthValueShadow3"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%Health%"
		"textAlignment"	         				 	"west"
		"font"                   				 	"m0refont32blur"
		"fgcolor"	     	         				"Black"

		"pin_to_sibling"							"PlayerStatusHealthValue"
	}
				"PlayerStatusHealthValueShadow4"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusHealthValueShadow4"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%Health%"
		"textAlignment"	         				 	"west"
		"font"                   				 	"m0refont32blur"
		"fgcolor"	     	         				"Black"

		"pin_to_sibling"							"PlayerStatusHealthValue"
	}
				"PlayerStatusHealthValueShadow5"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusHealthValueShadow5"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%Health%"
		"textAlignment"	         				 	"west"
		"font"                   				 	"m0refont32blur"
		"fgcolor"	     	         				"Black"

		"pin_to_sibling"							"PlayerStatusHealthValue"
	}
				"PlayerStatusHealthValueShadow6"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusHealthValueShadow6"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%Health%"
		"textAlignment"	         				 	"west"
		"font"                   				 	"m0refont32blur"
		"fgcolor"	     	         				"Black"

		"pin_to_sibling"							"PlayerStatusHealthValue"
	}
				"PlayerStatusHealthValueShadow7"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusHealthValueShadow7"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%Health%"
		"textAlignment"	         				 	"west"
		"font"                   				 	"m0refont32blur"
		"fgcolor"	     	         				"Black"

		"pin_to_sibling"							"PlayerStatusHealthValue"
	}
			"888"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"888"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"888"
		"textAlignment"	         				 	"west"
		"font"                   				 	"m0refont32blur"
		"fgcolor"	     	         				"Black"
		"alpha" "100"

		"pin_to_sibling"							"PlayerStatusHealthValue"
	}
	"PlayerStatusHealthValueShadowExtra"
	{
		"ControlName"	          				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusHealthValueShadowExtra"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%Health%"
		"textAlignment"	         				 	"west"
		"font"                   				 	"m0refont32blur"
		"fgcolor"	     	         				"Black"
		"alpha" "0"

		"pin_to_sibling"							"PlayerStatusHealthValueShadow"
	}
		"PlayerStatusMaxHealthValue"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue"
		"xpos"	    		         				"89"
		"ypos"	    		         				"7"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 "%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"white"

		"pin_to_sibling"							"PlayerStatusHealthValue"
	}
			"PlayerStatusMaxHealthValue1"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue1"
		"xpos"	    		         				"-1"
		"ypos"	    		         				"-1"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 "%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}
				"PlayerStatusMaxHealthValue2"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue2"
		"xpos"	    		         				"-1"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				"%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}
				"PlayerStatusMaxHealthValue3"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue3"
		"xpos"	    		         				"0"
		"ypos"	    		         				"-1"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 "%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}
				"PlayerStatusMaxHealthValue4"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue4"
		"xpos"	    		         				"1"
		"ypos"	    		         				"1"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				"%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}
				"PlayerStatusMaxHealthValue5"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue5"
		"xpos"	    		         				"1"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"149"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 "%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}
				"PlayerStatusMaxHealthValue5"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue5"
		"xpos"	    		         				"0"
		"ypos"	    		         				"1"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}
					"PlayerStatusMaxHealthValue6"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue6"
		"xpos"	    		         				"-1"
		"ypos"	    		         				"1"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 "%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}
					"PlayerStatusMaxHealthValue7"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue7"
		"xpos"	    		         				"1"
		"ypos"	    		         				"-1"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}
						"PlayerStatusMaxHealthValue8"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue8"
		"xpos"	    		         				"1"
		"ypos"	    		         				"-1"
		"zpos"	    		         				"5"
		"wide"		    	         				"149"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}
							"PlayerStatusMaxHealthValue9"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue9"
		"xpos"	    		         				"1"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"149"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}
								"PlayerStatusMaxHealthValue10"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"PlayerStatusMaxHealthValue10"
		"xpos"	    		         				"-1"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"151"
		"tall"		    	         				"80"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%MaxHealth%"
		"textAlignment"	         				 	"center"
		"font"                   				 	"m0refont10"
		"fgcolor"	     	         				"black"

		"pin_to_sibling"							"PlayerStatusMaxHealthValue"
	}

	//==================================================================================================================================================
	// STATUS ICONS ANCHOR
	// Moves all the status icons at the same time
	//==================================================================================================================================================

	"PlayerStatusAnchor"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"PlayerStatusAnchor"
		"xpos"										"-80"
		"ypos"										"-40"
		"wide"										"0"
		"tall"										"80"
		"visible"									"1"
		"enabled"									"1"

		"pin_to_sibling"							"PlayerStatusHealthValue"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	//==================================================================================================================================================
	// STATUS ICONS
	//==================================================================================================================================================

	"PlayerStatusBleedImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatusBleedImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../vgui/bleed_drop"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatusHookBleedImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusHookBleedImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"										"../vgui/bleed_drop_grapple"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatusGasImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatusGasImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../vgui/covered_in_gas"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatusMilkImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatusMilkImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../vgui/bleed_drop"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatusMarkedForDeathImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatusMarkedForDeathImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../vgui/marked_for_death"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatusMarkedForDeathSilentImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatusMarkedForDeathSilentImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../vgui/marked_for_death"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_MedicUberBulletResistImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_MedicUberBulletResistImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../HUD/defense_buff_bullet_blue"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_MedicUberBlastResistImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_MedicUberBlastResistImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../HUD/defense_buff_explosion_blue"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_MedicUberFireResistImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_MedicUberFireResistImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../HUD/defense_buff_fire_blue"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_MedicSmallBulletResistImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_MedicSmallBulletResistImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../HUD/defense_buff_bullet_blue"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_MedicSmallBlastResistImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_MedicSmallBlastResistImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../HUD/defense_buff_explosion_blue"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_MedicSmallFireResistImage"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_MedicSmallFireResistImage"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../HUD/defense_buff_fire_blue"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_WheelOfDoom"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_WheelOfDoom"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../signs/death_wheel_whammy"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_SoldierOffenseBuff"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_SoldierOffenseBuff"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../HUD/defense_buff_bullet_blue"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_SoldierDefenseBuff"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_SoldierDefenseBuff"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../HUD/defense_buff_bullet_blue"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_SoldierHealOnHitBuff"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_SoldierHealOnHitBuff"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../HUD/defense_buff_bullet_blue"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_Parachute"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_Parachute"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"0"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			""
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RuneStrength"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_RuneStrength"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../Effects/powerup_strength_hud"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RuneHaste"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_RuneHaste"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../Effects/powerup_haste_hud"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RuneRegen"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_RuneRegen"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../Effects/powerup_regen_hud"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RuneResist"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_RuneResist"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../Effects/powerup_resist_hud"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RuneVampire"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_RuneVampire"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../Effects/powerup_vampire_hud"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RuneReflect"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_RuneReflect"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"      								"../Effects/powerup_reflect_hud"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RunePrecision"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_RunePrecision"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"				         				"../Effects/powerup_precision_hud"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RuneAgility"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_RuneAgility"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../Effects/powerup_agility_hud"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RuneKnockout"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatus_RuneKnockout"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../Effects/powerup_knockout_hud"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneKing"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"					         		"PlayerStatus_RuneKing"
		"xpos"						         		"0"
		"ypos"						         		"0"
		"zpos"						         		"7"
		"wide"						         		"30"
		"tall"						         		"30"
		"visible"					         		"1"
		"enabled"					         		"1"
		"scaleImage"				         		"1"
		"image"						         		"../Effects/powerup_king_hud"
		"fgcolor"					         		"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RunePlague"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"					         		"PlayerStatus_RunePlague"
		"xpos"						         		"0"
		"ypos"						         		"0"
		"zpos"						         		"7"
		"wide"						         		"30"
		"tall"						         		"30"
		"visible"					         		"1"
		"enabled"					         		"1"
		"scaleImage"				         		"1"
		"image"						         		"../Effects/powerup_plague_hud"
		"fgcolor"					         		"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatus_RuneSupernova"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"					         		"PlayerStatus_RuneSupernova"
		"xpos"						         		"0"
		"ypos"						         		"0"
		"zpos"						         		"7"
		"wide"						         		"30"
		"tall"						         		"30"
		"visible"					         		"1"
		"enabled"					         		"1"
		"scaleImage"				         		"1"
		"image"						         		"../Effects/powerup_supernova_hud"
		"fgcolor"					         		"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	"PlayerStatusSlowed"
	{
		"ControlName"				         		"ImagePanel"
		"fieldName"				         			"PlayerStatusSlowed"
		"xpos"					         			"0"
		"ypos"					         			"0"
		"zpos"					         			"7"
		"wide"					         			"20"
		"tall"					         			"20"
		"visible"				         			"1"
		"enabled"				         			"1"
		"scaleImage"				         		"1"
		"image"					         			"../vgui/slowed"
		"fgcolor"				         			"TanDark"
		"pin_to_sibling"			         		"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}



	//==================================================================================================================================================
	// REMOVED ELEMENTS
	//==================================================================================================================================================

	"PlayerStatusHealthImage"
	{
		"ControlName" 	         				 	"ImagePanel"
		"fieldName"		          				 	"PlayerStatusHealthImage"
		"wide"		    	         				"0"
		"tall"                   				 	"0"
		"visible"		             				"0"
		"enabled"		             				"0"
		"xpos" "-25"
	}
	"PlayerStatusHealthImageBG"
	{
		"ControlName"	           				 	"ImagePanel"
		"fieldName"	  	         				 	"PlayerStatusHealthImageBG"
		"xpos"		    	          				"9999"
	}
}